### ISSUE TITLE
Branch name

### ISSUE THREAD

**Issue by erperejildo** [LevInteractive/stackahoy-cli#1]
I'm getting this issue:
```
Please make sure the branch name you provided is correct.
Tip: You can do `stackahoy list` to see what is available.
```
`stackahoy list` doesn't contain any further info

**Comment by psaia** [comment]
Are you passing in the token key? `stackahoy list -t YOUR_TOKEN`?

**Comment by erperejildo** [comment]
Yes, I'm passing token and repo id correctly

**Comment by psaia** [comment]
Could you please provide some information on your OS, npm version, and node version?

**Comment by erperejildo** [comment]
I'm right now using my laptop (Mac) and I've got no access to my computer (which is Windows).
Here I have no problem:
```
Started TaskList: Setup Docker
[138.68.171.51] - setup docker
[138.68.171.51] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[138.68.171.51] - Setup Environment

Started TaskList: Setup Mongo
[138.68.171.51] - setup environment
[138.68.171.51] - setup environment: SUCCESS
[138.68.171.51] - copying mongodb.conf
[138.68.171.51] - Setup Environment: SUCCESS
[138.68.171.51] - copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[138.68.171.51] - start mongo
[138.68.171.51] - start mongo: SUCCESS
```
I'll update info later on at home with my computer.

**Comment by erperejildo** [comment]
I'm having another issue running deploy but this is another different thing:
```
[138.68.171.51] x Verifying Deployment: FAILED
        
        -----------------------------------STDERR-----------------------------------
        package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
        => Starting meteor app on port:80
        
        assert.js:93
          throw new assert.AssertionError({
                ^
        AssertionError: "undefined" === "function"
            at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
            at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
            at Module._compile (module.js:456:26)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:364:17)
            at require (module.js:380:17)
            at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
            at Module._compile (module.js:456:26)
         
        => Redeploying previous version of the app
         
        -----------------------------------STDOUT-----------------------------------
        
        To see more logs type 'mup logs --tail=50'
        
        ----------------------------------------------------------------------------

```

**Comment by erperejildo** [comment]
Sorry @petesaia but I moved to mup a few days ago
